Feature/api
Maclenn77/hello-rails pull request #1
Opened 2022-04-09 06:19 UTC by Maclenn77

Hello, Microverse reviewers!

This is the backend of the development with react and rails. Find the PR of the frontend [here](https://github.com/Maclenn77/hellor-react/pull/1).

For this project, I :

-     Create a new Rails API app called 'hello-rails'.
-     Initialize the project with Git.
-     Postgres database set up.
-     Create a controller to create 5 different greetings.
-     Create an API endpoint that selects a random greeting.

The server is set up to open in 'localhost:3000'. Consume the API following /v1/greetings. Cors was configured to avoid cors problems.

2022-04-09 07:25 UTC, DeliceLydia requested changes
## Hi @Maclenn77, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-04-09 07:25 UTC, DeliceLydia commented on config/database.yml
> +  database: flatiron_mod3_production
- [ ] I am not able to create a database by running `rails db:create` kindly address that or add how you are doing it in your README

2022-04-10 00:53 UTC, Maclenn77 commented on config/database.yml
> +  database: flatiron_mod3_production
Hi, @DeliceLydia . Help me to understand the problem. 

What output are you expecting and what is it showing?

I don't have any problem when I run `rails db:create`.

2022-04-10 04:26 UTC, MrBrN197 approved these changes
## Hi, @Maclenn77   👋

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-10 04:26 UTC, MrBrN197 commented on db/seeds.rb
> +end
- [ ] [OPTIONAL] instead of using an outer variable to keep track of the index you can use the ruby method `each_with_index`
```suggestion


languages.each_with_index do |lang, index|
    Greeting.create(greeting: greetings[index],  language: lang)

end
```

2022-04-10 04:26 UTC, MrBrN197 commented on config/routes.rb
> +    end
- [ ] [OPTIONAL] I would recommend that you prefix your API routes under a `/api` namespace to make it clear that they are API routes.

2023-01-22 10:13 UTC, merged